/**
 * Automatic update by manifest — for internal distribution without a
 * marketplace: VS Code never updates an extension installed from a VSIX on
 * its own, so the extension takes care of it.
 *
 * The internal server hosts the VSIX and a `latest.json` manifest:
 *   { "version": "0.2.0", "vsix": "lutrin-vscode-0.2.0.vsix", "sha256": "…" }
 * (`vsix` may be relative to the manifest or absolute; generated by
 * `scripts/package.mjs --vsix`.)
 *
 * Threat model — the VSIX runs inside the extension host:
 *   - the sha256 digest (MANDATORY, verified on the downloaded buffer
 *     before any write to disk) protects against a corrupted download and
 *     against the compromise of a VSIX host distinct from the one
 *     serving the manifest;
 *   - it does NOT protect against a compromised manifest server: the digest
 *     travels in the same latest.json as the pointer — an attacker who
 *     controls the manifest supplies the digest of their own VSIX. Guarding
 *     against that would require a signature (key embedded in the
 *     extension);
 *   - http: URLs are refused (manifest AND VSIX): without TLS, a MITM would
 *     rewrite manifest and digest in a single stroke.
 *
 * `lutrin.updateUrl` points at the manifest; empty = disabled. Checked on
 * activation then every 24 h, and on demand through the "Check for Updates"
 * command. Installation goes through the built-in command
 * `workbench.extensions.installExtension` on the downloaded VSIX.
 */

import { createHash } from 'node:crypto';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import * as vscode from 'vscode';
import { type Manifest, isNewer, parseManifest, verifyDigest } from './updaterCore';

const CHECK_INTERVAL_MS = 24 * 60 * 60 * 1000;
const SKIPPED_KEY = 'lutrin.skippedVersion';

async function fetchManifest(url: string): Promise<Manifest> {
  const res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return parseManifest(await res.json(), url);
}

/** Downloads the VSIX and verifies its digest BEFORE writing it to disk.
 *  The write happens in a freshly created directory (mkdtemp) with the 'wx'
 *  flag: never overwriting a predictable path pre-created by a third party
 *  in the shared tmpdir. */
async function downloadVsix(url: string, manifest: Manifest): Promise<string> {
  const res = await fetch(url, { signal: AbortSignal.timeout(120_000) });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  verifyDigest(createHash('sha256').update(buffer).digest('hex'), manifest);
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'lutrin-vsix-'));
  const file = path.join(dir, `lutrin-vscode-${manifest.version}.vsix`);
  fs.writeFileSync(file, buffer, { flag: 'wx' });
  return file;
}

export class Updater implements vscode.Disposable {
  private timer: ReturnType<typeof setInterval> | null = null;
  private initialTimer: ReturnType<typeof setTimeout> | null = null;
  private readonly currentVersion: string;

  constructor(
    private readonly context: vscode.ExtensionContext,
    private readonly log: vscode.OutputChannel,
  ) {
    this.currentVersion = (context.extension.packageJSON as { version: string }).version;
  }

  /** Silent check on activation, then periodic. */
  start(): void {
    // slight delay so activation is not weighed down — kept so it can be
    // cancelled on deactivation (otherwise a check fires after the dispose)
    this.initialTimer = setTimeout(() => void this.check({ silent: true }), 10_000);
    this.timer = setInterval(() => void this.check({ silent: true }), CHECK_INTERVAL_MS);
  }

  private updateUrl(): string {
    return vscode.workspace.getConfiguration('lutrin').get<string>('updateUrl', '').trim();
  }

  /** silent: errors and "up to date" go to the output channel only. */
  async check({ silent }: { silent: boolean }): Promise<void> {
    const url = this.updateUrl();
    if (!url) {
      if (!silent)
        void vscode.window.showInformationMessage(
          'No update source configured (setting "lutrin.updateUrl").',
        );
      return;
    }
    if (!/^https:/i.test(url)) {
      const msg = `the update URL must be https (received: ${url}) — check refused`;
      this.log.appendLine(`update: ${msg}`);
      if (!silent) void vscode.window.showErrorMessage(`Lutrin — ${msg}`);
      return;
    }
    try {
      const manifest = await fetchManifest(url);
      if (!isNewer(manifest.version, this.currentVersion)) {
        this.log.appendLine(
          `update: ${this.currentVersion} is up to date (manifest: ${manifest.version})`,
        );
        if (!silent)
          void vscode.window.showInformationMessage(
            `Lutrin is up to date (${this.currentVersion}).`,
          );
        return;
      }
      if (silent && this.context.globalState.get<string>(SKIPPED_KEY) === manifest.version) return;

      const INSTALL = 'Update';
      const SKIP = 'Skip this version';
      const choice = await vscode.window.showInformationMessage(
        `Lutrin ${manifest.version} is available (installed: ${this.currentVersion}).`,
        INSTALL,
        SKIP,
      );
      if (choice === SKIP) {
        await this.context.globalState.update(SKIPPED_KEY, manifest.version);
        return;
      }
      if (choice !== INSTALL) return;

      const vsixUrl = new URL(manifest.vsix, url); // relative to the manifest, or absolute
      if (vsixUrl.protocol !== 'https:')
        throw new Error(`VSIX URL is not https (${vsixUrl.href}) — installation refused`);
      await vscode.window.withProgress(
        {
          location: vscode.ProgressLocation.Notification,
          title: `Updating to ${manifest.version}…`,
        },
        async () => {
          const file = await downloadVsix(vsixUrl.href, manifest);
          await vscode.commands.executeCommand(
            'workbench.extensions.installExtension',
            vscode.Uri.file(file),
          );
          fs.rmSync(path.dirname(file), { recursive: true, force: true });
        },
      );
      const RELOAD = 'Reload window';
      const reload = await vscode.window.showInformationMessage(
        `Version ${manifest.version} installed — reload to activate it.`,
        RELOAD,
      );
      if (reload === RELOAD) void vscode.commands.executeCommand('workbench.action.reloadWindow');
    } catch (e) {
      const msg = `update check: ${(e as Error).message}`;
      this.log.appendLine(msg);
      if (!silent) void vscode.window.showErrorMessage(`Lutrin — ${msg}`);
    }
  }

  dispose(): void {
    if (this.initialTimer) clearTimeout(this.initialTimer);
    if (this.timer) clearInterval(this.timer);
  }
}
